// Generated by typings
// Source: https://raw.githubusercontent.com/typed-typings/npm-is-callable/513a32746ada0fcba542ad7e18143878b97d387d/index.d.ts
declare module '~is-callable/index' {
function isCallable(callable: any): void;

export = isCallable;
}
declare module 'is-callable/index' {
import main = require('~is-callable/index');
export = main;
}
declare module 'is-callable' {
import main = require('~is-callable/index');
export = main;
}
